default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: JWExchange_development

test:
  <<: *default
  database: JWExchange_test

production:
  <<: *default
  database: JWExchange_production
  username: JWExchange
  password: <%= ENV['JWEXCHANGE_DATABASE_PASSWORD'] %>
